name    'puppet-groovy'
version '0.0.1'
source 'https://github.com/sherzberg/puppet-groovy'
author 'Spencer Herzberg'
license 'Apache License, Version 2.0'
summary 'Puppet module for installing Groovy from the official distribution.'
description 'This module installs Groovy from the offical project site.'
project_page 'https://github.com/sherzberg/puppet-groovy'

dependency 'smarchive/archive', '0.1.1'
